server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    gzip on;
    gzip_types text/css application/javascript image/svg+xml application/json image/png image/jpg image/webp;
    gzip_min_length 256;

    location /assets/ {
        expires 31536000s;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location /favicon.svg {
        expires -1;
        add_header Cache-Control "no-cache";
    }

    location / {
        expires -1;
        add_header Cache-Control "no-store";
        try_files $uri $uri/ /index.html;
    }
}